### ISSUE TITLE
goes off screen when 100 or more players

### ISSUE THREAD

**Issue by minipunch** [FAXES/fax-scoreboard#2]
should set overflow: scroll on the wrapper element

also get rid of `min-height` in favor of just `height`

**Comment by FAXES** [comment]
Cool suggestion. This is very old and out dated though. But will update this for these changes now.

**Comment by FAXES** [comment]
Added in commit https://github.com/FAXES/fax-scoreboard/commit/042f83270281493023fe00f45140a70d3ced1a2b
